export const lightTokens = {
  background: "#ffffff",
  foreground: "#09090b",
  primary: "#3b82f6",
  primaryForeground: "#ffffff",
  secondary: "#f4f4f5",
  secondaryForeground: "#18181b",
  muted: "#f4f4f5",
  mutedForeground: "#71717a",
  destructive: "#ef4444",
  destructiveForeground: "#ffffff",
  success: "#22c55e",
  successForeground: "#ffffff",
  warning: "#eab308",
  warningForeground: "#713f12",
  info: "#3b82f6",
  infoForeground: "#ffffff",
  border: "#e4e4e7",
  input: "#e4e4e7",
  ring: "#3b82f6",
} as const;

export const darkTokens = {
  background: "#09090b",
  foreground: "#fafafa",
  primary: "#3b82f6",
  primaryForeground: "#ffffff",
  secondary: "#27272a",
  secondaryForeground: "#fafafa",
  muted: "#27272a",
  mutedForeground: "#a1a1aa",
  destructive: "#ef4444",
  destructiveForeground: "#ffffff",
  success: "#22c55e",
  successForeground: "#ffffff",
  warning: "#eab308",
  warningForeground: "#713f12",
  info: "#3b82f6",
  infoForeground: "#ffffff",
  border: "#27272a",
  input: "#27272a",
  ring: "#3b82f6",
} as const;

export type Tokens = typeof lightTokens;
